version: "3.3"
services:
  hikvision-exporter-cam1:
    build: ./hikvision-exporter
    volumes:
      - type: volume
        source: hikvision_data
        target: /data
    environment:
      - HIKVISION_HOST=192.168.10.100
      - HIKVISION_PORT=554
      - HIKVISION_LOGIN=admin
      - HIKVISION_PASSWORD=12345
      - HIKVISION_CHANNEL=1
      - HIKVISION_STREAM=01
    restart: unless-stopped
  hikvision-exporter-cam2:
    build: ./hikvision-exporter
    volumes:
      - type: volume
        source: hikvision_data
        target: /data
    environment:
      - HIKVISION_HOST=192.168.10.100
      - HIKVISION_PORT=554
      - HIKVISION_LOGIN=admin
      - HIKVISION_PASSWORD=12345
      - HIKVISION_CHANNEL=2
      - HIKVISION_STREAM=01
    restart: unless-stopped
  hikvision-gdrive-uploader:
    build: ./hikvision-gdrive-uploader
    environment:
      - HIKVISION_GDRIVE_ROOT=hikvision
      - HIKVISION_DATA=/data
      - HIKVISION_UPLOAD_INTERVAL=1m
      - HIKVISION_DELETE_AFTER=18h
      - HIKVISION_GOOGLE_API_CREDENTIALS=/run/secrets/google_drive_credentials.json
      - HIKVISION_GOOGLE_API_TOKEN=/run/secrets/google_drive_token.json
    secrets:
      - google_drive_credentials.json
      - google_drive_token.json
    volumes:
      - type: volume
        source: hikvision_data
        target: /data
    restart: unless-stopped
volumes:
  hikvision_data:
secrets:
  google_drive_credentials.json:
    file: ./secrets/credentials.json
  google_drive_token.json:
    file: ./secrets/token.json

